<a href="https://colab.research.google.com/github/Jauny143/Machine-Learning-Projects/blob/main/Decision_tree_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#upload data from github
df = pd.read_csv('https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_15_decision_tree_classifier/iphone_purchase_records.csv')

In [5]:
df.head() #showing first five records

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   Salary           400 non-null    int64 
 3   Purchase Iphone  400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [17]:
X = df.iloc[:,:-1].values # independent features
y = df.iloc[:,3].values # Target

In [19]:
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [21]:
# convert age feature into numerical by using label encoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:,0] = label_encoder.fit_transform(X[:,0])

In [22]:
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [23]:
# spliting the dataset into train test variables
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [24]:
X_train 

array([[0, 44, 39000],
       [1, 32, 120000],
       [0, 38, 50000],
       [0, 32, 135000],
       [0, 52, 21000],
       [0, 53, 104000],
       [1, 39, 42000],
       [1, 38, 61000],
       [0, 36, 50000],
       [0, 36, 63000],
       [0, 35, 25000],
       [1, 35, 50000],
       [1, 42, 73000],
       [0, 47, 49000],
       [0, 59, 29000],
       [1, 49, 65000],
       [0, 45, 131000],
       [0, 31, 89000],
       [0, 46, 82000],
       [0, 47, 51000],
       [1, 26, 15000],
       [1, 60, 102000],
       [0, 38, 112000],
       [1, 40, 107000],
       [0, 42, 53000],
       [1, 35, 59000],
       [1, 48, 41000],
       [0, 48, 134000],
       [0, 38, 113000],
       [1, 29, 148000],
       [0, 26, 15000],
       [1, 60, 42000],
       [1, 24, 19000],
       [1, 42, 149000],
       [0, 46, 96000],
       [1, 28, 59000],
       [1, 39, 96000],
       [1, 28, 89000],
       [1, 41, 72000],
       [1, 45, 26000],
       [0, 33, 69000],
       [0, 20, 82000],
       [1, 31, 74000],


In [26]:
# using Decision tree calssifier

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 0)
classifier.fit(X_train,y_train)
 

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [27]:
y_pred = classifier.predict(X_test)

In [29]:
# calculate the performance

from sklearn import metrics
con_mat = metrics.confusion_matrix(y_test,y_pred)
con_mat

array([[63,  5],
       [ 3, 29]])

In [30]:
accuracy = metrics.accuracy_score(y_test,y_pred)

In [31]:
precison = metrics.precision_score(y_test,y_pred)

In [32]:
recall = metrics.recall_score(y_test,y_pred)

In [34]:
accuracy, precison, recall

(0.92, 0.8529411764705882, 0.90625)